"""
This module generates the Table of Contents (TOC) for the documentation.
"""

import os
from datetime import datetime
from file import render_tree_html
from config import config
from .generate_footer import generate_footer


def generate_toc(files):
    """
    Generates the Table of Contents (TOC) for the documentation.
    """
    name = find_name()
    header = generate_header(name)
    body = render_tree_html(files, config.documentation_suffix)
    footer = generate_footer(name, True)

    path = str(config.output_path) + os.sep + "index.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(body)
        f.write(footer)


def generate_header(name):
    """
    Generates the header for the Table of Contents (TOC).
    """
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = f"# Auto-generated Documentation for `{name}`\n"
    header += "This documentation is generated automatically from the source code. "
    header += "Do not edit this file directly.\n"

    return header


def find_name():
    """
    Finds the name of the project.
    """
    if config.gitmode:
        return os.path.basename(config.root_path)

    return os.path.basename(os.getcwd())
