"""
This module generates the footer for the documentation.
"""

import os
from datetime import datetime
from config import config


def generate_footer(name, root=False):
    """
    Generates the Footer.

    :param name: The name of the module for which the documentation is generated.
    :return: The formatted footer string for the documentation.
    """

    date = datetime.now().strftime("%B %d, %Y %H:%M:%S")
    full_name = f"{config.project_name}/{name}"

    if root:
        full_name = config.project_name

    footer = ""
    footer += "<br>\n"
    footer += "<br>\n"
    footer += "\n\n---\n"
    footer += f"### Automatically generated Documentation for `{full_name}`\n"
    footer += "This documentation is generated automatically from the source code. "
    footer += "Do not edit this file directly.\n"
    footer += f"Generated by **Doc-Buddy** on **{date}** via **{config.model}**\n\n"
    footer += "For more information, visit the [Doc-Buddy on GitHub](https://github.com/scott-r-lindsey/doc-buddy).  \n"

    if config.gitmode:
        repo_path = config.root_path
        githash = os.popen(f"\ncd {repo_path} && git rev-parse HEAD").read().strip()
        footer += f"*{config.project_name} Commit Hash: {githash}*\n"

    return footer
