"""
This module generates the Table of Contents (TOC) for the documentation.
"""

import os
from datetime import datetime
from config import config


def generate_footer(name):
    """
    Generates the Footer.

    :param name: The name of the module for which the documentation is generated.
    :return: The formatted footer string for the documentation.
    """
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    footer = "\n\n---\n"
    footer += f"### Auto-generated Documentation for {name}\n"
    footer += "This documentation is generated automatically from the source code. "
    footer += "Do not edit this file directly.\n"
    footer += f"Generated by Doc-Buddy on {date}\n\n"

    if config.gitmode:
        repo_path = config.root_path
        githash = os.popen(f"cd {repo_path} && git rev-parse HEAD").read().strip()
        footer += f"Git Hash: {githash}\n"

    return footer
